FROM golang:1.25.1-bookworm AS builder
RUN apt-get update && apt-get install -y curl clang gcc llvm make libbpf-dev git

WORKDIR /src
RUN git clone --depth 1 https://github.com/open-telemetry/opentelemetry-go-instrumentation.git .
RUN go generate ./... && go build -o otel-go-instrumentation ./cli/...

FROM gcr.io/distroless/base-debian12
COPY --from=builder /src/otel-go-instrumentation /
CMD ["/otel-go-instrumentation"]